server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # REST-CLIENT --> http://localhost:4004/api/v1/patients
        # API-GATEWAY --> http://patient-service:4000/v1/patients
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - StripPrefix=1
        # REST-CLIENT --> http://localhost:4004/api-docs/patients
        # API-GATEWAY --> http://patient-service:4000/api-docs/v3/api-docs
        - id: api-doc-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
