### POST request to create a patient
POST http://localhost:4004/api/v1/patients
Content-Type: application/json

{
  "name": "AKAP",
  "email": "kafka_consumer_test@email.com",
  "address": "Delhi",
  "registeredDate": "2025-04-11",
  "dateOfBirth": "2025-04-11"
}